-- ===========================================================
--                AGGREGATE QUERIES
--        Hospital Management System - PostgreSQL
-- ===========================================================


-- ===========================================================
-- Question 1:
-- Display total number of patients.
-- ===========================================================

SELECT
    COUNT(*) AS total_patients
FROM patients;


-- ===========================================================
-- Question 2:
-- Display total number of doctors.
-- ===========================================================

SELECT
    COUNT(*) AS total_doctors
FROM doctors;


-- ===========================================================
-- Question 3:
-- Display total number of appointments.
-- ===========================================================

SELECT
    COUNT(*) AS total_appointments
FROM appointments;


-- ===========================================================
-- Question 4:
-- Display total hospital revenue.
-- ===========================================================

SELECT
    SUM(total_amount) AS total_revenue
FROM billing;


-- ===========================================================
-- Question 5:
-- Display average bill amount.
-- ===========================================================

SELECT
    AVG(total_amount) AS average_bill
FROM billing;


-- ===========================================================
-- Question 6:
-- Display highest bill amount.
-- ===========================================================

SELECT
    MAX(total_amount) AS highest_bill
FROM billing;


-- ===========================================================
-- Question 7:
-- Display lowest bill amount.
-- ===========================================================

SELECT
    MIN(total_amount) AS lowest_bill
FROM billing;


-- ===========================================================
-- Question 8:
-- Display number of pending and paid bills.
-- ===========================================================

SELECT
    payment_status,
    COUNT(*) AS total_bills
FROM billing
GROUP BY payment_status;


-- ===========================================================
-- Question 9:
-- Display doctor-wise number of appointments.
-- ===========================================================

SELECT
    d.first_name || ' ' || d.last_name AS doctor_name,
    COUNT(a.appointment_id) AS total_appointments
FROM doctors d
JOIN appointments a
    ON d.doctor_id = a.doctor_id
GROUP BY d.doctor_id, doctor_name;


-- ===========================================================
-- Question 10:
-- Display department-wise number of doctors.
-- ===========================================================

SELECT
    dep.department_name,
    COUNT(d.doctor_id) AS total_doctors
FROM departments dep
JOIN doctors d
    ON dep.department_id = d.department_id
GROUP BY dep.department_name;


-- ===========================================================
-- Question 11:
-- Display total revenue generated by each doctor.
-- ===========================================================

SELECT
    d.first_name || ' ' || d.last_name AS doctor_name,
    SUM(b.total_amount) AS total_revenue
FROM doctors d
JOIN appointments a
    ON d.doctor_id = a.doctor_id
JOIN billing b
    ON a.appointment_id = b.appointment_id
GROUP BY d.doctor_id, doctor_name;


-- ===========================================================
-- Question 12:
-- Display number of patients per city.
-- ===========================================================

SELECT
    address,
    COUNT(*) AS total_patients
FROM patients
GROUP BY address;


-- ===========================================================
-- Question 13:
-- Display medicines count by type.
-- ===========================================================

SELECT
    medicine_type,
    COUNT(*) AS total_medicines
FROM medicines
GROUP BY medicine_type;


-- ===========================================================
-- Question 14:
-- Display total stock value of medicines.
-- ===========================================================

SELECT
    SUM(price * stock_quantity) AS total_stock_value
FROM medicines;


-- ===========================================================
-- Question 15:
-- Display appointments per status.
-- ===========================================================

SELECT
    status,
    COUNT(*) AS total
FROM appointments
GROUP BY status;